module.exports={
  mysql:{
    host:'101.251.102.37',
    user:'callcenter_rw',
    password:'callcenter_rw',
    port:'45728',
    database:'AndonCloud_New'
  },
  mysqlReadOnly:{
    host:'101.251.102.37',
    user:'callcenter_rw',
    password:'callcenter_rw',
    port:'45728',
    database:'AndonCloud_New'
  }
}
