module.exports={
  mysql:{
    host:'127.0.0.1',
    user:'admin',
    password:'admin',
    port:'3306',
    database:'test'
  },
  mysqlReadOnly:{
    host:'127.0.0.1',
    user:'admin',
    password:'admin',
    port:'3306',
    database:'test'
  }
}
