module.exports={
  mysql:{
    host:'127.0.0.1',
    user:'callcenter_rw',
    password:'callcenter_rw',
    port:'3306',
    database:'AndonCloud_New'
  },
  mysqlReadOnly:{
    host:'127.0.0.1',
    user:'callcenter_rw',
    password:'callcenter_rw',
    port:'3306',
    database:'AndonCloud_New'
  }
}
